// AUTO-GENERATED by fetch_schedule.py — do not edit by hand.
// St. Columbkille week: Corpus Christi Sunday · June 7, 2026
// https://www.saintcolumbkille.org/news/bulletin/1593-june-7-2026-corpus-christi/file

window.APP = {
  "title": "Mass Times",
  "region": "Omaha-area Catholic parishes",
  "week": "Corpus Christi Sunday · June 7, 2026",
  "presiderNote": "Presiding priests are listed for St. Columbkille; the other parishes publish Mass times only."
};

window.CHURCHES = [
  {
    "id": "columbkille",
    "name": "St. Columbkille",
    "town": "Papillion",
    "color": "#9E6B3F",
    "pastor": "Fr. Tom Greisen",
    "website": "https://www.saintcolumbkille.org",
    "bulletin": "https://www.saintcolumbkille.org/news/bulletin"
  },
  {
    "id": "matthew",
    "name": "St. Matthew",
    "town": "Bellevue",
    "color": "#5E7C6B",
    "pastor": "Fr. Leo Rigatuso",
    "website": "https://stmatthewbellevue.org",
    "bulletin": "https://stmatthewbellevue.org/news/bulletin"
  },
  {
    "id": "mary",
    "name": "St. Mary's",
    "town": "Bellevue",
    "color": "#8A5E72",
    "pastor": "Fr. Lydell Lape",
    "website": "https://stmarysbellevue.com",
    "bulletin": "https://stmarysbellevue.com/bulletin"
  },
  {
    "id": "patrick",
    "name": "St. Patrick",
    "town": "Gretna",
    "color": "#5C6E8C",
    "pastor": "Fr. Gregory Baxter",
    "website": "https://stpatricksgretna.org",
    "bulletin": "https://stpatricksgretna.org/bulletins/"
  }
];

window.PRIESTS = [
  {
    "id": "greisen",
    "name": "Fr. Tom Greisen",
    "role": "Pastor",
    "initials": "TG",
    "color": "#9E6B3F"
  },
  {
    "id": "moser",
    "name": "Fr. Patrick Moser",
    "role": "Associate Pastor",
    "initials": "PM",
    "color": "#5E7C6B"
  },
  {
    "id": "magnuson",
    "name": "Fr. Tom Magnuson",
    "role": "Retired",
    "initials": "TM",
    "color": "#5C6E8C"
  },
  {
    "id": "deacon",
    "name": "Deacon",
    "role": "Communion Service",
    "initials": "Dn",
    "color": "#8A5E72"
  }
];

window.DAYS = [
  {
    "id": 0,
    "short": "Sun",
    "long": "Sunday",
    "date": "June 7"
  },
  {
    "id": 1,
    "short": "Mon",
    "long": "Monday",
    "date": "June 8"
  },
  {
    "id": 2,
    "short": "Tue",
    "long": "Tuesday",
    "date": "June 9"
  },
  {
    "id": 3,
    "short": "Wed",
    "long": "Wednesday",
    "date": "June 10"
  },
  {
    "id": 4,
    "short": "Thu",
    "long": "Thursday",
    "date": "June 11"
  },
  {
    "id": 5,
    "short": "Fri",
    "long": "Friday",
    "date": "June 12"
  },
  {
    "id": 6,
    "short": "Sat",
    "long": "Saturday",
    "date": "June 13"
  }
];

window.MASSES = [
  {
    "church": "columbkille",
    "day": 0,
    "time": "07:30",
    "presider": "magnuson",
    "type": "Sunday Mass",
    "livestream": false,
    "intention": "Deceased"
  },
  {
    "church": "mary",
    "day": 0,
    "time": "08:00",
    "presider": null,
    "type": "Sunday Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "patrick",
    "day": 0,
    "time": "08:00",
    "presider": null,
    "type": "Sunday Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 0,
    "time": "09:00",
    "presider": "magnuson",
    "type": "Sunday Mass",
    "livestream": false,
    "intention": "+Al Ohmes"
  },
  {
    "church": "matthew",
    "day": 0,
    "time": "09:00",
    "presider": null,
    "type": "Sunday Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "mary",
    "day": 0,
    "time": "10:00",
    "presider": null,
    "type": "Sunday Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "patrick",
    "day": 0,
    "time": "10:00",
    "presider": null,
    "type": "Sunday Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 0,
    "time": "10:30",
    "presider": "moser",
    "type": "Sunday Mass",
    "livestream": false,
    "intention": "+Pam Ostransky"
  },
  {
    "church": "matthew",
    "day": 0,
    "time": "11:00",
    "presider": null,
    "type": "Sunday Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 0,
    "time": "12:00",
    "presider": "moser",
    "type": "Sunday Mass",
    "livestream": false,
    "intention": "+Delbert Ostergaard"
  },
  {
    "church": "mary",
    "day": 0,
    "time": "12:00",
    "presider": null,
    "type": "Sunday Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "patrick",
    "day": 0,
    "time": "12:00",
    "presider": null,
    "type": "Sunday Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "mary",
    "day": 0,
    "time": "13:30",
    "presider": null,
    "type": "Sunday Mass · Spanish",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 0,
    "time": "17:00",
    "presider": "greisen",
    "type": "Sunday Mass",
    "livestream": false,
    "intention": "Parishioners of"
  },
  {
    "church": "mary",
    "day": 1,
    "time": "07:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "patrick",
    "day": 1,
    "time": "07:30",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "mary",
    "day": 1,
    "time": "08:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 1,
    "time": "08:15",
    "presider": "greisen",
    "type": "Daily Mass",
    "livestream": true,
    "intention": "+Yinh Lai"
  },
  {
    "church": "matthew",
    "day": 1,
    "time": "09:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 1,
    "time": "17:30",
    "presider": "magnuson",
    "type": "Daily Mass",
    "livestream": false,
    "intention": "+Rita Griffin"
  },
  {
    "church": "mary",
    "day": 2,
    "time": "07:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "mary",
    "day": 2,
    "time": "08:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 2,
    "time": "08:15",
    "presider": "magnuson",
    "type": "Daily Mass",
    "livestream": true,
    "intention": "+Pham V. Bach"
  },
  {
    "church": "matthew",
    "day": 2,
    "time": "09:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 2,
    "time": "17:30",
    "presider": "greisen",
    "type": "Daily Mass",
    "livestream": false,
    "intention": "+Helen & Bill Lenagh"
  },
  {
    "church": "patrick",
    "day": 2,
    "time": "18:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "mary",
    "day": 3,
    "time": "07:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "patrick",
    "day": 3,
    "time": "07:30",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 3,
    "time": "08:15",
    "presider": "greisen",
    "type": "Daily Mass",
    "livestream": true,
    "intention": "Blessings for the"
  },
  {
    "church": "mary",
    "day": 3,
    "time": "08:30",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "matthew",
    "day": 3,
    "time": "09:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 3,
    "time": "17:30",
    "presider": "magnuson",
    "type": "Daily Mass",
    "livestream": false,
    "intention": "+Tom Farrell"
  },
  {
    "church": "mary",
    "day": 4,
    "time": "07:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "patrick",
    "day": 4,
    "time": "07:30",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "mary",
    "day": 4,
    "time": "08:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 4,
    "time": "08:15",
    "presider": "greisen",
    "type": "Daily Mass",
    "livestream": true,
    "intention": "+Mary Ann Nowak"
  },
  {
    "church": "matthew",
    "day": 4,
    "time": "09:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "mary",
    "day": 5,
    "time": "07:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "patrick",
    "day": 5,
    "time": "07:30",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "mary",
    "day": 5,
    "time": "08:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 5,
    "time": "08:15",
    "presider": "magnuson",
    "type": "Daily Mass",
    "livestream": true,
    "intention": "+Patricia Nolan"
  },
  {
    "church": "matthew",
    "day": 5,
    "time": "09:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "mary",
    "day": 6,
    "time": "08:00",
    "presider": null,
    "type": "Daily Mass",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 6,
    "time": "08:15",
    "presider": "deacon",
    "type": "Communion Service",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 6,
    "time": "17:00",
    "presider": "greisen",
    "type": "Vigil",
    "livestream": true,
    "intention": "+Larry Deane"
  },
  {
    "church": "mary",
    "day": 6,
    "time": "17:00",
    "presider": null,
    "type": "Vigil",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "matthew",
    "day": 6,
    "time": "17:00",
    "presider": null,
    "type": "Vigil",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "patrick",
    "day": 6,
    "time": "17:00",
    "presider": null,
    "type": "Vigil",
    "livestream": false,
    "intention": ""
  },
  {
    "church": "columbkille",
    "day": 6,
    "time": "18:30",
    "presider": "greisen",
    "type": "Vigil",
    "livestream": false,
    "intention": "+Barb Nelson"
  }
];
