// AUTO-GENERATED by fetch_schedule.py — do not edit by hand.
// St. Columbkille week: None
// source: https://www.saintcolumbkille.org/news/bulletin/1610-june-28-2026-13th-sunday-in-ordinary-time/file
// source: https://www.saintcolumbkille.org/news/bulletin/1607-june-21-2026-12th-sunday-in-ordinary-time/file

window.APP = {
  "title": "Mass Times",
  "region": "Omaha-area Catholic parishes",
  "week": null,
  "presiderNote": "Presiding priests are listed for St. Columbkille; the other parishes publish Mass times only.",
  "columbkilleCoverage": {
    "start": "2026-06-22",
    "end": "2026-07-05"
  }
};

window.CHURCHES = [
  {
    "id": "columbkille",
    "name": "St. Columbkille",
    "town": "Papillion",
    "color": "#9E6B3F",
    "pastor": "Fr. Tom Greisen",
    "website": "https://www.saintcolumbkille.org",
    "bulletin": "https://www.saintcolumbkille.org/news/bulletin"
  },
  {
    "id": "matthew",
    "name": "St. Matthew",
    "town": "Bellevue",
    "color": "#5E7C6B",
    "pastor": "Fr. Leo Rigatuso",
    "website": "https://stmatthewbellevue.org",
    "bulletin": "https://stmatthewbellevue.org/news/bulletin"
  },
  {
    "id": "mary",
    "name": "St. Mary's",
    "town": "Bellevue",
    "color": "#8A5E72",
    "pastor": "Fr. Lydell Lape",
    "website": "https://stmarysbellevue.com",
    "bulletin": "https://stmarysbellevue.com/bulletin"
  },
  {
    "id": "patrick",
    "name": "St. Patrick",
    "town": "Gretna",
    "color": "#5C6E8C",
    "pastor": "Fr. Gregory Baxter",
    "website": "https://stpatricksgretna.org",
    "bulletin": "https://stpatricksgretna.org/bulletins/"
  }
];

window.PRIESTS = [
  {
    "id": "greisen",
    "name": "Fr. Tom Greisen",
    "role": "Pastor",
    "initials": "TG",
    "color": "#9E6B3F"
  },
  {
    "id": "moser",
    "name": "Fr. Patrick Moser",
    "role": "Associate Pastor",
    "initials": "PM",
    "color": "#5E7C6B"
  },
  {
    "id": "magnuson",
    "name": "Fr. Tom Magnuson",
    "role": "Retired",
    "initials": "TM",
    "color": "#5C6E8C"
  },
  {
    "id": "deacon",
    "name": "Deacon",
    "role": "Communion Service",
    "initials": "Dn",
    "color": "#8A5E72"
  },
  {
    "id": "gutgsell",
    "name": "Fr. Gutgsell",
    "role": "Visiting priest",
    "initials": "Gu",
    "color": "#7A6BA8"
  },
  {
    "id": "eischeid",
    "name": "Fr. Eischeid",
    "role": "Visiting priest",
    "initials": "Ei",
    "color": "#3F7A8C"
  },
  {
    "id": "reddy",
    "name": "Fr. Reddy",
    "role": "Visiting priest",
    "initials": "Re",
    "color": "#A8743F"
  }
];

window.DATED_MASSES = [
  {
    "church": "columbkille",
    "date": "2026-06-22",
    "time": "08:15",
    "presider": "greisen",
    "type": "Daily Mass",
    "livestream": true
  },
  {
    "church": "columbkille",
    "date": "2026-06-22",
    "time": "17:30",
    "presider": "magnuson",
    "type": "Daily Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-23",
    "time": "08:15",
    "presider": "moser",
    "type": "Daily Mass",
    "livestream": true
  },
  {
    "church": "columbkille",
    "date": "2026-06-23",
    "time": "17:30",
    "presider": "greisen",
    "type": "Daily Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-24",
    "time": "08:15",
    "presider": "greisen",
    "type": "Daily Mass",
    "livestream": true
  },
  {
    "church": "columbkille",
    "date": "2026-06-24",
    "time": "17:30",
    "presider": "moser",
    "type": "Daily Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-25",
    "time": "08:15",
    "presider": "moser",
    "type": "Daily Mass",
    "livestream": true
  },
  {
    "church": "columbkille",
    "date": "2026-06-25",
    "time": "17:30",
    "presider": "magnuson",
    "type": "Daily Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-26",
    "time": "06:20",
    "presider": "moser",
    "type": "Daily Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-26",
    "time": "08:15",
    "presider": "magnuson",
    "type": "Daily Mass",
    "livestream": true
  },
  {
    "church": "columbkille",
    "date": "2026-06-27",
    "time": "08:15",
    "presider": "deacon",
    "type": "Communion Service",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-27",
    "time": "17:00",
    "presider": "moser",
    "type": "Vigil",
    "livestream": true
  },
  {
    "church": "columbkille",
    "date": "2026-06-27",
    "time": "18:30",
    "presider": "reddy",
    "type": "Vigil",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-28",
    "time": "07:30",
    "presider": "moser",
    "type": "Sunday Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-28",
    "time": "09:00",
    "presider": "reddy",
    "type": "Sunday Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-28",
    "time": "10:30",
    "presider": "magnuson",
    "type": "Sunday Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-28",
    "time": "12:00",
    "presider": "magnuson",
    "type": "Sunday Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-28",
    "time": "17:00",
    "presider": "reddy",
    "type": "Sunday Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-29",
    "time": "08:15",
    "presider": "magnuson",
    "type": "Daily Mass",
    "livestream": true
  },
  {
    "church": "columbkille",
    "date": "2026-06-29",
    "time": "17:30",
    "presider": "gutgsell",
    "type": "Daily Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-06-30",
    "time": "08:15",
    "presider": "moser",
    "type": "Daily Mass",
    "livestream": true
  },
  {
    "church": "columbkille",
    "date": "2026-06-30",
    "time": "17:30",
    "presider": "magnuson",
    "type": "Daily Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-07-01",
    "time": "08:15",
    "presider": "moser",
    "type": "Daily Mass",
    "livestream": true
  },
  {
    "church": "columbkille",
    "date": "2026-07-01",
    "time": "17:30",
    "presider": "eischeid",
    "type": "Daily Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-07-02",
    "time": "08:15",
    "presider": "eischeid",
    "type": "Daily Mass",
    "livestream": true
  },
  {
    "church": "columbkille",
    "date": "2026-07-02",
    "time": "17:30",
    "presider": "moser",
    "type": "Daily Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-07-03",
    "time": "08:15",
    "presider": "moser",
    "type": "Daily Mass",
    "livestream": true
  },
  {
    "church": "columbkille",
    "date": "2026-07-04",
    "time": "09:00",
    "presider": "moser",
    "type": "Daily Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-07-04",
    "time": "17:00",
    "presider": "eischeid",
    "type": "Vigil",
    "livestream": true
  },
  {
    "church": "columbkille",
    "date": "2026-07-04",
    "time": "18:30",
    "presider": "moser",
    "type": "Vigil",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-07-05",
    "time": "07:30",
    "presider": "moser",
    "type": "Sunday Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-07-05",
    "time": "09:00",
    "presider": "eischeid",
    "type": "Sunday Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-07-05",
    "time": "10:30",
    "presider": "eischeid",
    "type": "Sunday Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-07-05",
    "time": "12:00",
    "presider": "moser",
    "type": "Sunday Mass",
    "livestream": false
  },
  {
    "church": "columbkille",
    "date": "2026-07-05",
    "time": "17:00",
    "presider": "magnuson",
    "type": "Sunday Mass",
    "livestream": false
  }
];

window.WEEKLY_MASSES = [
  {
    "church": "matthew",
    "day": 6,
    "time": "17:00",
    "type": "Vigil"
  },
  {
    "church": "matthew",
    "day": 0,
    "time": "09:00",
    "type": "Sunday Mass"
  },
  {
    "church": "matthew",
    "day": 0,
    "time": "11:00",
    "type": "Sunday Mass"
  },
  {
    "church": "matthew",
    "day": 1,
    "time": "09:00",
    "type": "Daily Mass"
  },
  {
    "church": "matthew",
    "day": 2,
    "time": "09:00",
    "type": "Daily Mass"
  },
  {
    "church": "matthew",
    "day": 3,
    "time": "09:00",
    "type": "Daily Mass"
  },
  {
    "church": "matthew",
    "day": 4,
    "time": "09:00",
    "type": "Daily Mass"
  },
  {
    "church": "matthew",
    "day": 5,
    "time": "09:00",
    "type": "Daily Mass"
  },
  {
    "church": "patrick",
    "day": 6,
    "time": "17:00",
    "type": "Vigil"
  },
  {
    "church": "patrick",
    "day": 0,
    "time": "08:00",
    "type": "Sunday Mass"
  },
  {
    "church": "patrick",
    "day": 0,
    "time": "10:00",
    "type": "Sunday Mass"
  },
  {
    "church": "patrick",
    "day": 0,
    "time": "12:00",
    "type": "Sunday Mass"
  },
  {
    "church": "patrick",
    "day": 1,
    "time": "07:30",
    "type": "Daily Mass"
  },
  {
    "church": "patrick",
    "day": 2,
    "time": "18:00",
    "type": "Daily Mass"
  },
  {
    "church": "patrick",
    "day": 3,
    "time": "07:30",
    "type": "Daily Mass"
  },
  {
    "church": "patrick",
    "day": 4,
    "time": "07:30",
    "type": "Daily Mass"
  },
  {
    "church": "patrick",
    "day": 5,
    "time": "07:30",
    "type": "Daily Mass"
  },
  {
    "church": "mary",
    "day": 6,
    "time": "17:00",
    "type": "Vigil"
  },
  {
    "church": "mary",
    "day": 0,
    "time": "08:00",
    "type": "Sunday Mass"
  },
  {
    "church": "mary",
    "day": 0,
    "time": "10:00",
    "type": "Sunday Mass"
  },
  {
    "church": "mary",
    "day": 0,
    "time": "12:00",
    "type": "Sunday Mass"
  },
  {
    "church": "mary",
    "day": 0,
    "time": "13:30",
    "type": "Sunday Mass · Spanish"
  },
  {
    "church": "mary",
    "day": 1,
    "time": "07:00",
    "type": "Daily Mass"
  },
  {
    "church": "mary",
    "day": 1,
    "time": "08:00",
    "type": "Daily Mass"
  },
  {
    "church": "mary",
    "day": 2,
    "time": "07:00",
    "type": "Daily Mass"
  },
  {
    "church": "mary",
    "day": 2,
    "time": "08:00",
    "type": "Daily Mass"
  },
  {
    "church": "mary",
    "day": 3,
    "time": "07:00",
    "type": "Daily Mass"
  },
  {
    "church": "mary",
    "day": 3,
    "time": "08:30",
    "type": "Daily Mass"
  },
  {
    "church": "mary",
    "day": 4,
    "time": "07:00",
    "type": "Daily Mass"
  },
  {
    "church": "mary",
    "day": 4,
    "time": "08:00",
    "type": "Daily Mass"
  },
  {
    "church": "mary",
    "day": 5,
    "time": "07:00",
    "type": "Daily Mass"
  },
  {
    "church": "mary",
    "day": 5,
    "time": "08:00",
    "type": "Daily Mass"
  },
  {
    "church": "mary",
    "day": 6,
    "time": "08:00",
    "type": "Daily Mass"
  }
];
